### ISSUE TITLE
give an option to run few commands as "root" user

### ISSUE THREAD

**Issue by linianq** [IBM/txseries-docker-container#1]
Currently setup.sh script runs as CICS region user "txadmin". But we need to run some commands as "root" user, for example: "ulimit -s 1024", to ensure we can start more cicsas(50+).

**Comment by kishkulk** [comment]
@linianq  If you want to set ulimit to a container then you should use --ulimit argument with docker run command.
For example the bellow docker run will start the container with 1024K of stack size
```sh
docker run -it --ulimit stack=1048576:1048576 -e LICENSE=accept ibmcom/txseries
```

**Comment by kishkulk** [comment]
We have even provided the option of running the root user commands before configuring the region. You have to write all the root user command into /work/pre_setup_root_config.sh which will be run before configuring the TXSeries region 
For example if you have written the root user commands into /home/linianq/root-command.sh then run the following run command
```sh
docker run -it -e LICENSE=accept -v  /home/linianq/root-command.sh:/work/pre_setup_root_config.sh ibmcom/txseries
```
the above container will run the /work/pre_setup_root_config.sh before configuring the region. 

Note: You should use absolute path in the root commands script ( /work/pre_setup_root_config.sh )
